POST http://localhost:3333/videos
Content-Type: application/json


{
    "title": "Video node",
    "description": "My video description",
    "duration": 120
}   



###

GET  http://localhost:3333/videos?search=node
 

###

PUT http://localhost:3333/videos/76cb12ba-c24c-416b-82e7-a9fc57c7e443
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Meu vídeo 01",
    "duration": 120
}   

###

DELETE http://localhost:3333/videos/b740beff-ee02-492e-a349-dcbefbab26a8

###

