POST http://localhost:3333/videos
Content-Type: application/json


{
    "title": "Video database",
    "description": "Teste database",
    "duration": 120
}   



###

GET  http://localhost:3333/videos
 

###

PUT http://localhost:3333/videos/f993929e-2f80-4060-800e-421876764d9d
Content-Type: application/json

{
    "title": "Video alterado",
    "description": "Minha primeira alteração",
    "duration": 120
}   

###

DELETE http://localhost:3333/videos/b740beff-ee02-492e-a349-dcbefbab26a8

###

