POST https://nodetest-cbwh.onrender.com/videos
Content-Type: application/json


{
    "title": "Video database",
    "description": "Teste database",
    "duration": 120
}   



###

GET  https://nodetest-cbwh.onrender.com/videos
 

###

PUT https://nodetest-cbwh.onrender.com/videos/53967051-c076-491b-91c2-63899b6a4165
Content-Type: application/json

{
    "title": "Video alterado 02",
    "description": "Minha segunda alteração",
    "duration": 120
}   

###

DELETE https://nodetest-cbwh.onrender.com/videos/f993929e-2f80-4060-800e-421876764d9d

###

